---

version: "3.2"

services:
  elasticsearch:
    image: elasticsearch
    ports:
      - 9200:9200
  es-client:
    build:
      context: .
      args:
        http_proxy:
        no_proxy:
    environment:
      ES_CLUSTER: http://localhost:9200
      ELM_ES_PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app